### ISSUE TITLE
DatabaseCleaner.clean sometimes fails with undefined method "database_type"

### ISSUE THREAD

**Issue by joshuaswilcox** [DatabaseCleaner/database_cleaner-sequel#4]
For some reason DatabaseCleaner.clean fails occasionally with this error:

```
  Failure/Error: DatabaseCleaner.clean
  NoMethodError:
    undefined method `database_type' for :default:Symbol
  # /Users/jwilcox/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/sequel/truncation.rb:58:in `txid'
  # /Users/jwilcox/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/sequel/truncation.rb:54:in `dirty?'
  # /Users/jwilcox/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/sequel/truncation.rb:15:in `clean'
  # /Users/jwilcox/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/base.rb:92:in `clean'
  # /Users/jwilcox/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:79:in `block in clean'
  # /Users/jwilcox/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:79:in `each'
  # /Users/jwilcox/.rvm/gems/ruby-2.3.1/gems/database_cleaner-1.5.3/lib/database_cleaner/configuration.rb:79:in `clean'
  # ./spec/spec_helper.rb:48:in `block (2 levels) in <top (required)>'
```

I am using the Sequel gem and have rspec configured with

```
  config.before(:suite) do
    DatabaseCleaner.strategy = :truncation
  end

  config.after(:each) do |example|
    DatabaseCleaner.clean
  end
```

The tests that fail are not even using and database operations, they are just unit tests

**Comment by khiav223577** [comment]
I got this error randomly, too. And it only occurs in one specific test case.

My setting:
`spec/support/database_cleaner.rb`
```rb
RSpec.configure do |config|
  config.before(:suite) do
    DatabaseCleaner.strategy = :transaction
    DatabaseCleaner.clean_with(:truncation)
  end

  config.before(:each) do
    DatabaseCleaner.start
  end

  config.after(:each) do
    DatabaseCleaner.clean
  end
end
```

The only test case that is possible to get this error:
![image](https://user-images.githubusercontent.com/4011729/76346596-3f57d900-6340-11ea-8fba-60713c84bc8c.png)

**Comment by botandrose** [comment]
@khiav223577 I see that you're using database_cleaner v1.7.0. Can you try with latest v1.8 release (and/or database_cleaner-sequel gem) and tell me if the issue still is occurring?

**Comment by botandrose** [comment]
@khiav223577 Looking at your backtrace more closely, you appear to be using the ActiveRecord adapter, not the Sequel adapter, so this is not the bug for you! :)

Can you open an issue on https://github.com/DatabaseCleaner/database_cleaner-active_record instead?

**Comment by botandrose** [comment]
@benoror Can you see if https://github.com/DatabaseCleaner/database_cleaner-sequel/pull/11 fixes your issue?

**Comment by khiav223577** [comment]
> @khiav223577 Looking at your backtrace more closely, you appear to be using the ActiveRecord adapter, not the Sequel adapter, so this is not the bug for you! :)
> 
> Can you open an issue on https://github.com/DatabaseCleaner/database_cleaner-active_record instead?

Thanks for your quick reply. I'll try the latest version of database_cleaner and submit another issue if the issue still exists.
